stages:
  - chaos

chaos_pod_kill:
  stage: chaos
  image: alpine:latest
  tags:
    - chaos-runner       # (옵션) GitLab Runner 태그
  before_script:
    - apk add --no-cache ansible kubectl openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - export ANSIBLE_HOST_KEY_CHECKING=False
  script:
    - echo "🚀 Running Chaos Pod Kill test..."
    - ansible-playbook -i inventory/hosts.ini playbooks/chaos/run_pod_kill.yml \
        -e "execution_mode=${EXECUTION_MODE:-sequential}" \
        -e "@pod_kill_targets.yml"
  only:
    - main
    - chaos-test

