# ─────────────────────────────────────────────
# recommendationservice Deployment & Service
# ─────────────────────────────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: app
  labels:
    app: recommendationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      serviceAccountName: default
      containers:
        - name: recommendationservice
          image: seongmin14/recommendationservice:v0.10.4
          ports:
            - containerPort: 8080
          env:
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
          readinessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: 8080
          livenessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: app
  labels:
    app: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080

